- hosts: all
  become: true


  vars_prompt:
    - name: "usuario"
      prompt: "Usuario al que cambiar la contrase単a"
      private: no

  vars:
    salt: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"


    derived_pass_plain: "{{ inventory_hostname[0:3] | upper }}info2025"


    derived_pass_hash: "{{ derived_pass_plain | password_hash('sha512', salt) }}"

  tasks:
    - name: Mostrar contrase単a derivada (solo para DEBUG; quitar en prod)
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Contrase単a plana: {{ derived_pass_plain }}"

    - name: Cambiar la contrase単a del usuario
      user:
        name: "{{ usuario }}"
        password: "{{ derived_pass_hash }}"
