- hosts: all
  become: true
  vars:
    salt: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"
    hashed_pass: "{{ nueva_senha | password_hash('sha512', salt) }}"
  tasks:
    - name: Cambiar la contraseña del usuario
      user:
        name: "{{ usuario }}"
        password: "{{ hashed_pass }}"