---
- name: Mostrar bases de datos MySQL en todos los hosts
  hosts: all
  gather_facts: no
  vars_prompt:
    - name: mysql_root_password
      prompt: "Contraseña del usuario root de MySQL"
      private: yes

  tasks:
    - name: Ejecutar SHOW DATABASES
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        query: "SHOW DATABASES;"
      register: result

    - name: Mostrar resultados
      debug:
        var: result.query_result
