---
- name: Configurar Sistema de Monitorización
  hosts: monitoring_servers
  become: true
  tasks:
    - name: Instalar Docker
      package:
        name: docker-ce
        state: present
        
    - name: Instalar docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        
    - name: Crear directorio para Prometheus
      file:
        path: /opt/prometheus
        state: directory
        
    - name: Copiar archivo docker-compose
      template:
        src: templates/docker-compose-monitoring.yml.j2
        dest: /opt/prometheus/docker-compose.yml
        
    - name: Copiar configuración de Prometheus
      template:
        src: templates/prometheus.yml.j2
        dest: /opt/prometheus/prometheus.yml
        
    - name: Levantar servicios de monitorización
      command: docker-compose up -d
      args:
        chdir: /opt/prometheus